function txt = myupdatefcn(~,event_obj,Dosis)
% Customizes text of data tips
pos = get(event_obj,'Position');
%I = get(event_obj, 'DataIndex');
txt = {['X: ',num2str(pos(1))],...
       ['Y: ',num2str(pos(2))],...
       ['Dosis_voxel: ',num2str(Dosis.total(pos(1),pos(2)))],...
       ['X: ',num2str(pos(1))]};
end